# Generate src-reverie/reverie/config.reo from reverie.conf (JSON).
#
# RingEcho has no runtime JSON parser, so configuration is resolved at build
# time into a generated .reo module. Missing reverie.conf keeps the committed
# default.
#
# -Dev points the window at the frontend dev server (asset.devUrl) so HMR works.
param([switch]$Dev)
$ErrorActionPreference = 'Continue'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$appRoot = Split-Path -Parent $here
$conf = Join-Path $appRoot 'reverie.conf'
$out = Join-Path $appRoot 'src-reverie/reverie/config.reo'

if (-not (Test-Path $conf)) {
    Write-Host "gen-config: no reverie.conf, keeping default config"
    exit 0
}

$json = Get-Content -LiteralPath $conf -Raw | ConvertFrom-Json

function Esc([string]$value) {
    if ($null -eq $value) { return '' }
    return $value.Replace('\', '\\').Replace('"', '\"')
}

$title = $json.window.title
if (-not $title) { $title = $json.name }
if (-not $title) { $title = 'Reverie App' }

$width = 900
if ($json.window.width) { $width = [int]$json.window.width }
$height = 600
if ($json.window.height) { $height = [int]$json.window.height }

$assetHost = 'reverie.local'
if ($json.asset.host) { $assetHost = $json.asset.host }
$assetFolder = 'dist'
if ($json.asset.folder) { $assetFolder = $json.asset.folder }
# Kept as configured (usually relative). The runtime resolves a relative folder
# against the executable's directory, so the same build works from any install
# location.
$assetFolder = ($assetFolder -replace '\\', '/')

$hosts = @('reverie.local')
if ($json.security.allowedHosts) { $hosts = @($json.security.allowedHosts) }

$devUrl = 'http://localhost:5173'
if ($json.asset.devUrl) { $devUrl = $json.asset.devUrl }
if ($Dev) {
    $windowUrl = $devUrl
    # The dev server host must be allowed by the navigation policy.
    $devHost = ([System.Uri]$devUrl).Host
    if ($devHost -and ($hosts -notcontains $devHost)) { $hosts += $devHost }
} else {
    $windowUrl = "https://$assetHost/index.html"
}

$text = "// Generated by scripts/gen-config.ps1 from reverie.conf. Do not edit.`n`n"
$text += "fn reverie_cfg_title() -> str { return `"$(Esc $title)`"; }`n"
$text += "fn reverie_cfg_width() -> i32 { return $width; }`n"
$text += "fn reverie_cfg_height() -> i32 { return $height; }`n"
$text += "fn reverie_cfg_asset_host() -> str { return `"$(Esc $assetHost)`"; }`n"
$text += "fn reverie_cfg_asset_folder() -> str { return `"$(Esc $assetFolder)`"; }`n"
$text += "fn reverie_cfg_window_url() -> str { return `"$(Esc $windowUrl)`"; }`n"

function Flag($value, $default) {
    if ($null -eq $value) { return $default }
    if ($value -eq $true) { return 1 }
    return 0
}
$text += "fn reverie_cfg_decorations() -> i32 { return $(Flag $json.window.decorations 1); }`n"
$text += "fn reverie_cfg_resizable() -> i32 { return $(Flag $json.window.resizable 1); }`n"
$text += "fn reverie_cfg_always_on_top() -> i32 { return $(Flag $json.window.alwaysOnTop 0); }`n"
$text += "fn reverie_cfg_fullscreen() -> i32 { return $(Flag $json.window.fullscreen 0); }`n`n"
$text += "fn reverie_cfg_apply_security() {`n"
foreach ($allowedHost in $hosts) {
    $text += "    reverie_allow_host(`"$(Esc $allowedHost)`");`n"
}
$text += "}`n"

[System.IO.File]::WriteAllText($out, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "gen-config: wrote $out"
