// Generate src-reverie/reverie/config.reo from reverie.conf (JSON).
//
// Cross-platform counterpart of scripts/gen-config.ps1, used by build-app.sh.
// RingEcho has no runtime JSON parser, so configuration is resolved at build
// time into a generated .reo module. A missing reverie.conf keeps the committed
// default.
//
//   node scripts/gen-config.mjs [--dev]
//
// --dev points the window at the frontend dev server (asset.devUrl) for HMR.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = dirname(here);
const conf = join(appRoot, "reverie.conf");
const out = join(appRoot, "src-reverie", "reverie", "config.reo");
const dev = process.argv.includes("--dev");

if (!existsSync(conf)) {
  console.log("gen-config: no reverie.conf, keeping default config");
  process.exit(0);
}

const json = JSON.parse(readFileSync(conf, "utf8"));
const esc = (value) => (value == null ? "" : String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"'));

const win = json.window ?? {};
const asset = json.asset ?? {};
const security = json.security ?? {};

const title = win.title || json.name || "Reverie App";
const width = win.width ? parseInt(win.width, 10) : 900;
const height = win.height ? parseInt(win.height, 10) : 600;
const assetHost = asset.host || "reverie.local";
const assetFolder = String(asset.folder || "dist").replace(/\\/g, "/");
const hosts = Array.isArray(security.allowedHosts) ? [...security.allowedHosts] : ["reverie.local"];
const devUrl = asset.devUrl || "http://localhost:5173";

let windowUrl;
if (dev) {
  windowUrl = devUrl;
  try {
    const devHost = new URL(devUrl).hostname;
    if (devHost && !hosts.includes(devHost)) hosts.push(devHost);
  } catch {
    // leave hosts as-is for an unparseable devUrl
  }
} else {
  windowUrl = `https://${assetHost}/index.html`;
}

const flag = (value, fallback) => (value == null ? fallback : value === true ? 1 : 0);

let text = "// Generated by scripts/gen-config.mjs from reverie.conf. Do not edit.\n\n";
text += `fn reverie_cfg_title() -> str { return "${esc(title)}"; }\n`;
text += `fn reverie_cfg_width() -> i32 { return ${width}; }\n`;
text += `fn reverie_cfg_height() -> i32 { return ${height}; }\n`;
text += `fn reverie_cfg_asset_host() -> str { return "${esc(assetHost)}"; }\n`;
text += `fn reverie_cfg_asset_folder() -> str { return "${esc(assetFolder)}"; }\n`;
text += `fn reverie_cfg_window_url() -> str { return "${esc(windowUrl)}"; }\n`;
text += `fn reverie_cfg_decorations() -> i32 { return ${flag(win.decorations, 1)}; }\n`;
text += `fn reverie_cfg_resizable() -> i32 { return ${flag(win.resizable, 1)}; }\n`;
text += `fn reverie_cfg_always_on_top() -> i32 { return ${flag(win.alwaysOnTop, 0)}; }\n`;
text += `fn reverie_cfg_fullscreen() -> i32 { return ${flag(win.fullscreen, 0)}; }\n\n`;
text += "fn reverie_cfg_apply_security() {\n";
for (const host of hosts) text += `    reverie_allow_host("${esc(host)}");\n`;
text += "}\n";

writeFileSync(out, text);
console.log(`gen-config: wrote ${out}`);
